Fix copying course chapter id in exercises (#1030)
* Fix copying course chapter id in exercises

* Update seed order numbers

* Revert "Update seed order numbers"

This reverts commit 284c456bfc7ae274fdbfc2d94f6fcdbf868cd510.

* Fix

* Update detect dev env problems

* Add docker desktop detection for linux

* Fix exercise task numbers

* Update print-versions

* Note bin/print-versions in the documentation

* Update installation documentation

* Typo fix

* Update installation documentation

* Update installation documentation

* Automatically cancel system tests for old commits on pull requests

diff --git a/bin/seed b/bin/seed
--- a/bin/seed
+++ b/bin/seed
@@ -5,4 +5,11 @@ source "$(dirname "$0")/.common"
 POD_NAME=$(kubectl get pods -l app=headless-lms -o name --sort-by=.metadata.creationTimestamp | tac | head -n 1)
 [ -z "$POD_NAME" ] && { echo "Failed to find pod name. Note that this command assumes you have the headless-lms pod running."; exit 1; }
 
-run_command kubectl exec -it "$POD_NAME" "$@" -- cargo run -- seed "$@"
+NUMBER_OF_CARGO_FILES=$(kubectl exec -it "$POD_NAME" -- ls | grep -c Cargo.toml || true)
+
+if [ "$NUMBER_OF_CARGO_FILES" -eq "0" ]; then
+  echo "Error: this command is meant to be used with bin/dev but you have bin/test running. Please use bin/setup-system-test-db or switch to bin/dev."
+  exit 255
+fi
+
+run_command kubectl exec -it "$POD_NAME" -- cargo run -- seed "$@"
