Authenticate to Google Cloud just before push

diff --git a/.github/workflows/system-tests.yml b/.github/workflows/system-tests.yml
--- a/.github/workflows/system-tests.yml
+++ b/.github/workflows/system-tests.yml
@@ -22,20 +22,6 @@ jobs:
           kubectl: "1.19.2"
           kustomize: "4.1.3"
           skaffold: "1.24.0"
-
-      - name: Authenticate to Google Cloud
-        env:
-          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
-        run: |
-          echo Authenticating to Google Cloud
-          echo $GCLOUD_SERVICE_KEY | python -m base64 -d > /tmp/key.json
-          gcloud auth activate-service-account --key-file=/tmp/key.json
-          if gcloud auth configure-docker -q; then
-              echo "Authenticated to Google Cloud..."
-          else
-              echo "Authentication to Google Cloud failed. Exiting..."
-              exit 1
-          fi
       - name: Workaround for kube-proxy set nf_conntrack_max permission denied
         run: |
           # Workarounds this issue when starting up kube-system/kube-proxy:
@@ -95,6 +81,21 @@ jobs:
       - name: Run system tests
         run: npm run test
         working-directory: ./system-tests/
+
+      - name: Authenticate to Google Cloud
+        env:
+          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
+        run: |
+          echo Authenticating to Google Cloud
+          echo $GCLOUD_SERVICE_KEY | python -m base64 -d > /tmp/key.json
+          gcloud auth activate-service-account --key-file=/tmp/key.json
+          if gcloud auth configure-docker -q; then
+              echo "Authenticated to Google Cloud..."
+          else
+              echo "Authentication to Google Cloud failed. Exiting..."
+              exit 1
+          fi
+        if: ${{ github.ref == 'refs/heads/master' }}
 
       - name: Push images if master
         run: skaffold build -p test,push-images
